on:
  issue_comment:
    types: [created]

name: "Vouch - Manage by Issue"

concurrency:
  group: vouch-manage
  cancel-in-progress: false

permissions:
  contents: write
  issues: write
  pull-requests: read

jobs:
  manage:
    runs-on: namespace-profile-ghostty-xsm
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: mitchellh/vouch/action/manage-by-issue@daa39f90448eb4054ad334d7f53959a7efb5005b # v1.4.0
        with:
          repo: ${{ github.repository }}
          issue-id: ${{ github.event.issue.number }}
          comment-id: ${{ github.event.comment.id }}
          vouch-keyword: "!vouch"
          denounce-keyword: "!denounce"
          unvouch-keyword: "!unvouch"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
